# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#es:
#  languageCode: es
#  contentDir: content/es
#  title: Julissa Villanueva 
#  params:
#    description: Portafolio de Julissa
#  menu:
#    main:
#      - name: Julissa
#        url: '#sobre'
#        weight: 1
